language: elixir
otp_release:
 - 18.3
 - 19.2
 - 19.3
elixir:
 - 1.4.2
branches:
  only:
    - master
before_install:
 - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip
 - unzip gnatsd-v0.9.6-linux-amd64.zip
 - ./gnatsd-v0.9.6-linux-amd64/gnatsd &

before_script:
 - ./gnatsd-v0.9.6-linux-amd64/gnatsd -p 4223 --user bob --pass alice &
 - ./gnatsd-v0.9.6-linux-amd64/gnatsd -p 4224 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem &
 - ./gnatsd-v0.9.6-linux-amd64/gnatsd -p 4225 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem --tlscacert test/fixtures/ca.pem --tlsverify &

script:
  - mix test --include multi_server
