version: 2.1

default_version: &default_version 1.8.1

jobs:
  build:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      - run: wget https://github.com/nats-io/gnatsd/releases/download/v1.4.1/gnatsd-v1.4.1-linux-amd64.zip
      - run: unzip gnatsd-v1.4.1-linux-amd64.zip
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4223 --user bob --pass alice
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4224 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4225 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem --tlscacert test/fixtures/ca.pem --tlsverify
          background: true
      - restore_cache:
          keys:
            #- v1-{{ parameters.version }}-{{ checksum "mix.lock" }} # how we will cache dialyzer stuff
            - v1-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: MIX_ENV=test mix do deps.get, compile
      - save_cache:
          key: v1-{{ checksum "mix.lock" }}
          paths:
          - "deps"
          - "_build"
          - "~/.mix"
      - run: mix test --include multi_server

workflows:
  version: 2.1
  testing_all_versions:
    jobs:
      - build:
          name: "Test Elixir 1.8.1"
          version: 1.8.1